### ISSUE TITLE
How to use this with safetensors files?

### ISSUE THREAD

**Issue by syddharth** [lopho/stable-diffusion-prune#2]
I get the following error when using a safetensors and saving as a safetensors:
```
Traceback (most recent call last):
  File "C:\AI\SD\_source\Prune\stable-diffusion-prune\prune.py", line 124, in <module>
    main(sys.argv[1:])
  File "C:\AI\SD\_source\Prune\stable-diffusion-prune\prune.py", line 113, in main
    load(args.input, pickle_module = torch_pickle), # type: ignore
  File "C:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
AttributeError: type object 'torch_pickle' has no attribute 'load'
```

**Comment by lopho** [comment]
`safetensors` loading is not supported yet.

**Comment by lopho** [comment]
if you want to prune a safetensors file right now, you'd have to convert it to a format supported by pytorch.

**Comment by syddharth** [comment]
Understood. Thanks for the update.

**Comment by lopho** [comment]
as of commit https://github.com/lopho/stable-diffusion-prune/commit/8ed86151e34cbd8ac6824b50ebffec9af7fbcb48
using safetensors should work now
